FROM bitwalker/alpine-elixir-phoenix:1.6.5 as builder

ENV PORT=4000 \
    MIX_ENV=dev

RUN mkdir /app
WORKDIR /app
ADD . /app

RUN mix do local.hex --force, local.rebar --force
RUN mix do deps.get, deps.compile

WORKDIR /app/apps/magasin_web/assets

RUN npm i -g npm@6.1.0
RUN npm install

WORKDIR /app

EXPOSE 4000

CMD ["/bin/bash"]
