version: '3'

services:
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: magasin_dev
      PGDATA: /pgdata
    volumes:
      - ../magasin_pgdata:/pgdata

  application:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    volumes:
      - .:/app
      - node_modules:/app/magasin_web/assets/node_modules
      - static:/app/magasin_web/priv/static
      - deps:/app/deps
      - _build:/app/_build
    ports:
      - "4000:4000"
    depends_on:
      - db

volumes:
  node_modules:
  static:
  _build:
  deps:
