version: '3'

services:
  db:
    image: postgres:10.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      PGDATA: /pgdata
    volumes:
      # Persist data in a local folder: this allows us to have access to it even if we blow
      # away Docker
      - ./pgdata:/pgdata

  application:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      # Mount the application: allows us to update files on the host without copying them into the image
      - .:/app
      # Let Docker persist dependencies and builds:
      # * if we blow away Docker this can be easily recreated
      # * it keeps all build concerns separate from the host operating system
      # * for compiled dependencies, stop conflicts with different host OS
      # * maps to a subset of directories in .gitignore
      - node_modules:/app/apps/magasin_web/assets/node_modules
      - static:/app/apps/magasin_web/priv/static
      - deps:/app/deps
      - _build:/app/_build
    ports:
      - "4000:4000"
    depends_on:
      - db
    tty: true

# volumes defined for use in above configuration
volumes:
  node_modules:
  static:
  _build:
  deps:
