version: 2

jobs:
  build:
    environment:
      - MIX_ENV: "test"
    docker:
      # Use CircleCI specific images:
      # - provide `dockerize` used command below
      # - for more information see https://circleci.com/docs/2.0/circleci-images/
      - image: civilcode/elixir-ci:1.6.5a
      - image: circleci/postgres:10.4
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: acme_test
          POSTGRES_PASSWORD: postgres
    working_directory: ~/repo
    steps:
      - checkout
      - run: cp config/test.secret.exs.ci config/test.secret.exs
      - run: mix do local.hex --force, local.rebar --force
      - restore_cache: # restore saved dependency cache
          keys:
            - v4-dep-cache-{{ checksum "mix.lock" }}
            - v4-dep-cache-{{ .Branch }}
            - v4-dep-cache
      - restore_cache:  # restores saved build cache
          keys:
            - v4-build-and-mix-cache-{{ .Branch }}
            - v4-build-and-mix-cache
      - run: mix do deps.get, compile --warnings-as-errors
      - save_cache: # save dependencies to cache
          key: v4-dep-cache-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache: # save dependencies to cache
          key: v4-dep-cache-{{ .Branch }}
          paths: "deps"
      - save_cache: # save dependencies to cache
          key: v4-dep-cache
          paths: "deps"
      - save_cache: # save build cache
          key: v4-build-and-mix-cache-{{ .Branch }}
          paths:
            - _build
            - ~/.mix
      - save_cache: # save build cache
          key: v4-build-and-mix-cache
          paths:
            - _build
            - ~/.mix
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: mix hex.audit
      - run: mix format --check-formatted
      - run: mix coveralls.circle --umbrella
      - run: mix credo --strict
      - run: mix project.seed
      - run: mix cmd --app magasin_web mix sobelow --compact --exit Low
      - run: sudo apk add --update --no-cache rsync
      - run:
           command: |
              ./bin/project.new -c starbucks -a physical-store -g civilcode/star-bucks-platform -Y -Q -r .
              cd ../starbucks-platform
              echo "use Mix.Config
              config :physical_store, PhysicalStore.Repo,
                adapter: Ecto.Adapters.Postgres,
                database: \"acme_test\",
                hostname: \"localhost\",
                username: \"postgres\",
                password: \"postgres\",
                pool: Ecto.Adapters.SQL.Sandbox" > config/test.secret.exs
              mix do deps.get, test
