version: 2

jobs:
  build:
    environment:
      - MIX_ENV: "test"
    docker:
      - image: circleci/elixir:1.6.4
      - image: circleci/postgres:10.1-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: magasin_test
          POSTGRES_PASSWORD: postgres

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo
    steps:
      - checkout
      - run: cp config/test.secret.exs.ci config/test.secret.exs
      - run: mix do local.hex --force, local.rebar --force
      - restore_cache: # restore saved dependency cache
          keys:
            - v2-dep-cache-{{ checksum "mix.lock" }}
            - v2-dep-cache-{{ .Branch }}
            - v2-dep-cache
      - restore_cache:  # restores saved build cache
          keys:
            - v2-build-and-mix-cache-{{ .Branch }}
            - v2-build-and-mix-cache
      - run: mix do deps.get, compile --warnings-as-errors
      - run: mix dialyzer --halt-exit-status
      - save_cache: # save dependencies to cache
          key: v2-dep-cache-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache: # save dependencies to cache
          key: v2-dep-cache-{{ .Branch }}
          paths: "deps"
      - save_cache: # save dependencies to cache
          key: v2-dep-cache
          paths: "deps"
      - save_cache: # save build cache
          key: v2-build-and-mix-cache-{{ .Branch }}
          paths:
            - _build
            - ~/.mix
      - save_cache: # save build cache
          key: v2-build-and-mix-cache
          paths:
            - _build
            - ~/.mix
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: mix credo --strict
